[package]
name = "wasm-runtime"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
bytemuck = "1.13.1"
# Code from this is actually never used BUT it is used by the node graph code!
vorpal-wasm-builtins = { path = "../../vorpal/vorpal-wasm-builtins" }
